OBJS = StringsAndArrows.o
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

StringsAndArrows : $(OBJS)
		   $(CC) $(LFLAGS) $(OBJS) -o StringsAndArrows

StringsAndArrows.o : StringsAndArrows.cpp
			 $(CC) $(CFLAGS) StringsAndArrows.cpp
			 
clean:
	\rm *.o *~ StringsAndArrows